[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install gunicorn",
  "pip install -r deployment/requirements.txt"
]

[start]
cmd = "cd deployment && python app/main.py"

