[build]
builder = "nixpacks"
watch = ["deployment/app/**", "deployment/requirements.txt"]

[deploy]
startCommand = "cd deployment && python app/main.py"
watch = ["deployment/app/**"]

[env]
FLASK_ENV = "production"
PORT = "8080"

